version: '3.3'

services:

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

  php-my-admin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    # Map host port 8080 to container port 80.
    ports:
      - 8080:80
    links:
      - db

  # Container to run cli applications (composer, drush, drupal-console, etc.)
  php-cli:
    # Here, we use a Dockerfile and not a Docker Image. The file is Dockerfile-php-cli and is in the same repository
    # as the docker-compose.yml
    build:
      context: .
      dockerfile: Dockerfile-php-cli
      # Arguments passed to the Dockerfile.
      args:
        USER_UID: ${USER_UID}
    volumes:
      # Data of application
      - .:/var/www/html:rw
      # Share the local user's composer cache and settings
      - ~/.composer:/home/php/.composer:rw
      # Share the local user's npm cache as a Docker volume
      - ~/.npm:/home/php/.npm:rw
      # Share the local user's SSH keys and configuration (read-only)
      - ~/.ssh:/home/php/.ssh:ro
      # Share the local user's known_host
      - ~/.ssh/known_hosts:/home/php/.ssh/known_hosts:rw
      # Share the local user's gitconfig
      - ~/.gitconfig:/home/php/.gitconfig
    environment:
      # We define the PATH and add the bin directory of vendor.
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/html/vendor/bin
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    links:
      - db

  php-fpm:
    image: drupaldocker/php-dev:${PHP_VERSION_TAG}-fpm
    volumes:
      - .:/var/www/html:rw
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    links:
      - db

  # Web server.
  web:
    image: drupaldocker/nginx
    environment:
      DOCROOT: /var/www/html/web
    ports:
      - ${PORT}:80
    volumes:
      - .:/var/www/html:rw
    links:
      - php-fpm:php
